// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBihbeMy2CPOq9xwuAAgSFvq0FhQgauOHc',
    appId: '1:286032108765:web:0c9cf93d60716a1ca10f34',
    messagingSenderId: '286032108765',
    projectId: 'wh40k-stratagems',
    authDomain: 'wh40k-stratagems.firebaseapp.com',
    storageBucket: 'wh40k-stratagems.appspot.com',
    measurementId: 'G-Y1SG90D036',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMEfjxVTF91tMID_lZeGvkXyMeAAayoxI',
    appId: '1:286032108765:android:b85b1f99f73e98fea10f34',
    messagingSenderId: '286032108765',
    projectId: 'wh40k-stratagems',
    storageBucket: 'wh40k-stratagems.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALVXPEpvyTtNf7faJHcLaXUo2dSP8oNfk',
    appId: '1:286032108765:ios:cd7ab69c429309b0a10f34',
    messagingSenderId: '286032108765',
    projectId: 'wh40k-stratagems',
    storageBucket: 'wh40k-stratagems.appspot.com',
    iosClientId: '286032108765-u3qulk73cdrc9r9fgg89d9ct2l38ibjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.battleBreGems',
  );
}
